title = "Prakti"
baseURL = "https://prakti.me"
tags = ["learn", "practice"]
languageCode = "en-US"
config = "config.toml"
theme = "osprey"
canonifyURLS = true
googleAnalytics = "UA-135929486-1"
disqusShortname = ""
disableKinds = ["taxonomy", "taxonomyTerm"] # This theme does not currently use "tag" and "category" taxonomies

[Params]
  tagline = "Life Takes Practice"
  author = "Tom Counsell"
  description = "Highly Effective People Striving to Reach 100%"
  logoBig = "/images/logo-square.png"
  logoSmall = "/images/triangle.jpg"
  favicon = "favicon.ico"
  opengraphImage = "/images/triangle.png"
  email = "info@prakti.me"
  googleTagManger = ""
  customCSS = false

  # Social media links in footer
  twitter = ""
  linkedin = ""
  github = "yudame"
  facebook = ""

  # Copyright and theme author credit in footer
  copyright = true
  copyright_business = "Yudame Inc"
  credit = false

  # Cache busting of static resources (additional set up required)
  cacheBustCSS = false
  cacheBustJS = false

  # Code highlighting with highlight.js
  highlightJS = true
  highlightJSStyle = "" # For custom highlight.js styles, add your /path/to/styles/default.css
  highlightJSScript = "" # For custom highlight.js languages config, add your /path/to/highlight.pack.js

  # Choose either Formspree contact form or Basin contact form
  ajaxFormspree = false
  ajaxFormspreeGold = false
  ajaxBasin = ""

[[menu.main]]
  name = "About"
  url  = "/#about"
  weight = 1
[[menu.main]]
  name = "Prague Meetups"
  url  = "https://meetup.com/prakti-prague"
  weight = 2
# [[menu.main]]
#   name = "Miami Sessions"
#   url  = "/#blog"
#   weight = 3
# [[menu.main]]
#   name = "Contact"
#   url  = "/#contact"
#   weight = 4
